var annotated_dup =
[
    [ "Aircraft", "class_aircraft.html", "class_aircraft" ],
    [ "AircraftMover", "struct_aircraft_mover.html", "struct_aircraft_mover" ],
    [ "Command", "struct_command.html", "struct_command" ],
    [ "CommandQueue", "class_command_queue.html", "class_command_queue" ],
    [ "CrateApp", "class_crate_app.html", "class_crate_app" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "FrameResource", "struct_frame_resource.html", "struct_frame_resource" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameState", "class_game_state.html", "class_game_state" ],
    [ "MenuState", "class_menu_state.html", "class_menu_state" ],
    [ "ObjectConstants", "struct_object_constants.html", "struct_object_constants" ],
    [ "PassConstants", "struct_pass_constants.html", "struct_pass_constants" ],
    [ "PauseState", "class_pause_state.html", "class_pause_state" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "RenderItem", "struct_render_item.html", "struct_render_item" ],
    [ "sceneNode", "classscene_node.html", "classscene_node" ],
    [ "SpriteNode", "class_sprite_node.html", "class_sprite_node" ],
    [ "State", "class_state.html", "class_state" ],
    [ "StateStack", "class_state_stack.html", "class_state_stack" ],
    [ "TitleState", "class_title_state.html", "class_title_state" ],
    [ "Vertex", "struct_vertex.html", "struct_vertex" ],
    [ "World", "class_world.html", "class_world" ]
];